CREATE DATABASE Jaegers;

CREATE TABLE Jaegers
(
	id SERIAL PRIMARY KEY,
	modelName VARCHAR NOT NULL,
	mark VARCHAR NOT NULL,
	height DECIMAL NOT NULL,
	weight DECIMAL NOT NULL,
	status VARCHAR NOT NULL,
	origin VARCHAR NOT NULL,
	launch DATE NOT NULL,
	kaijuKill INTEGER NOT NULL
);